main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Jacoobes
description: math in the command line
commands:
  ex:
    description: Base command for EXAMPLE
    usage: "To get 2, /eval 1 + 1"
    aliases: example
permissions:
  example.test:
    description: DESCRIPTION
    default: true
  example.*:
    description: Grants all other permissions
    default: false
    children:
      example.test: true