main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Jacoobes
description: math in the command line
commands:
  eval:
    description: Evaluate math on the command lnie
    usage: "To get 2, /eval 1 + 1"
permissions:
  eval.test:
    description: DESCRIPTION
    default: true
  eval.*:
    description: Grants all other permissions
    default: false
    children:
      eval.test: true